ALTER TABLE `item` ADD `description` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `iteminstance` ADD `name` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `iteminstance` ADD `description` VARCHAR(255) NULL DEFAULT NULL;
